export const constants = {
  journalPrompts: [
    'What are you grateful for today?',
    'Describe a challenge you overcame recently.',
    'Write about a person who has had a significant impact on your life and why.',
    'What are your top priorities for this week?',
    'Describe a moment that made you smile today.',
    'Reflect on a mistake you made and what you learned from it.',
    'Write about a book or article you read recently and its impact on you.',
    'What are your short-term and long-term goals?',
    'Describe a place you would like to visit and why.',
    'Write a letter to your future self.',
    'What are you passionate about, and why?',
    'Describe your ideal day from start to finish.',
    'Reflect on a fear you have and how you can overcome it.',
    'Write about a hobby or activity you enjoy and why.',
    'What are some things that make you unique?',
    'Describe a favorite childhood memory.',
    'Write about a time when you felt proud of yourself.',
    'What motivates you to keep going when things get tough?',
    'Reflect on a decision you made recently. Was it the right one?',
    'Write about a time when you helped someone or were helped by someone.',
    'What are you excited about for the future?',
    'Describe a moment when you felt at peace.',
    'Write about a lesson you learned from a difficult experience.',
    'What are your favorite ways to relax and unwind?',
    'Reflect on a quote that inspires you and why it resonates with you.',
    'Describe a dream you had recently and its significance to you.',
    'Write about a person you admire and why.',
    'What are some things you would like to improve about yourself?',
    'Describe a place that makes you feel calm and happy.',
    'Write about a goal you accomplished and how it made you feel.',
    'What are your biggest strengths and weaknesses?',
    'Reflect on a time when you felt truly alive.',
    'What are your favorite memories with friends or family?',
    "Describe a challenge you're currently facing and brainstorm ways to overcome it.",
    'Write about a time when you felt grateful for something small.',
    'What are your favorite ways to practice self-care?',
    'Reflect on a time when you took a risk and what you gained from it.',
    'Describe a favorite tradition or ritual you have.',
    'Write about a skill you would like to learn and why.',
    'What are your favorite things about yourself?',
    "Describe a goal you've been procrastinating on and why.",
    'Reflect on a time when you felt inspired by someone.',
    'What are your favorite quotes and why?',
    'Write about a place you feel nostalgic for and why.',
    'What are your biggest accomplishments so far?',
    "Describe a time when you felt grateful for someone's kindness.",
    'Reflect on a decision you regret and what you learned from it.',
    'Write about a time when you pushed yourself out of your comfort zone.',
    'What are your favorite ways to spend quality time with loved ones?',
    'Describe a moment when you felt truly appreciated.',
    'Write about a goal you set for yourself and how you plan to achieve it.',
    'What are your favorite things to do on a lazy day?',
    'Reflect on a time when you felt inspired by nature.',
    "Describe a challenge you're currently facing and what you've learned from it so far.",
    'What are your favorite memories from childhood?',
    'Write about a lesson you learned from a mistake.',
    'What are your favorite ways to practice mindfulness?',
    'Reflect on a time when you felt proud of someone else.',
    'Describe a moment when you felt like you were in the right place at the right time.',
    'Write about a goal you achieved despite obstacles in your way.',
    'What are your favorite ways to express creativity?',
    'Describe a time when you felt completely in sync with someone else.',
    'Reflect on a time when you received unexpected help.',
    'What are your favorite ways to stay motivated?',
    "Write about a challenge you're currently facing and how you plan to overcome it.",
    "What are your favorite things to do when you're feeling stressed?",
    'Describe a moment when you felt deeply connected to someone.',
    'Reflect on a time when you received constructive criticism.',
    'What are your favorite ways to stay focused and productive?',
    "Write about a goal you've been putting off and why.",
    'What are your favorite ways to show appreciation for others?',
    "Describe a time when you felt proud of someone else's accomplishment.",
    'Reflect on a time when you felt truly understood.',
    'What are your favorite ways to stay positive?',
    'Write about a challenge you faced and how it changed you.',
    'What are your favorite ways to stay healthy?',
    'Describe a moment when you felt like you were exactly where you were meant to be.',
    'Reflect on a time when you had to stand up for what you believe in.',
    'What are your favorite ways to practice gratitude?',
    'Write about a goal you achieved that you once thought was impossible.',
    'What are your favorite ways to stay inspired?',
    'Describe a time when you felt like you were part of something bigger than yourself.',
    'Reflect on a time when you felt proud of your progress.',
    'What are your favorite ways to overcome self-doubt?',
    'Write about a challenge you faced and how it strengthened you.',
    'What are your favorite ways to recharge and rejuvenate?',
    'Describe a moment when you felt deeply connected to your surroundings.',
    'Reflect on a time when you had to let go of something or someone.',
    'What are your favorite ways to celebrate your successes?',
    'Write about a goal you achieved through perseverance.',
    'What are your favorite ways to cultivate positivity in your life?',
    'Describe a time when you felt grateful for a second chance.',
    "Reflect on a time when you felt like giving up but didn't.",
    'What are your favorite ways to stay grounded?',
    'Write about a challenge you faced that ultimately led to growth.',
    'What are your favorite ways to practice patience?',
    'Describe a moment when you felt like you were living in the present.',
    'Reflect on a time when you felt proud of your resilience.',
    'What are your favorite ways to stay true to yourself?',
    'Write about a goal you achieved despite doubters or setbacks.',
    'What are your favorite ways to cultivate kindness towards yourself and others?',
    'Describe a time when you felt grateful for a difficult experience.',
    'Reflect on a time when you felt like you were exactly where you needed to be.',
    'What are your favorite ways to stay connected with your values?',
    'Write about a challenge you faced that taught you the importance of perseverance.',
    'What are your favorite ways to practice self-reflection?',
    'Describe a moment when you felt grateful for the people in your life.',
    'Reflect on a time when you felt proud of your growth.',
    'What are your favorite ways to stay resilient in the face of adversity?',
    'Write about a goal you achieved that surprised even yourself.',
  ],
};
